package ru.ertelecom.kafka.extract.pixel_pagetracking.domain

import ru.ertelecom.kafka.extract.core.serde.SerializableMessage

case class PixelDomRuPagetracking(
    log_entry_date: String,
    ts: Long,
    p_uid: Option[String],
    client_id: Option[String],
    client_id_b2b: Option[String],
    javaenabled: String,
    flashversion: Option[String],
    lang: Option[String],
    screencolors: Option[String],
    screenresolution: Option[String],
    windowresolution: Option[String],
    codepage: Option[String],
    ua: String,
    ip: Long,
    url: String,
    hostname: Option[String],
    pathtopage: Option[String],
    screenview: Option[String],
    title: Option[String],
    web_id: Option[String],
    user_id: Option[String],
    ref: Option[String],
    hit_type: Option[String],
    pageloadtime: Option[Int],
    pagedownloadtime: Option[Int],
    redirectresponcetime: Option[Int],
    serverresponcetime: Option[Int],
    contentloadtime: Option[Int],
    event_category: Option[String],
    event_action: Option[String],
    event_label: Option[String],
    event_value: Option[String],
    http_ref: Option[String],
    gtm: Option[String],
    citydomain: Option[String],
    browser_name: Option[String],
    browser_version: Option[String],
    os_name: Option[String],
    os_version: Option[String],
    device: Option[String]
) extends SerializableMessage {}
